### ISSUE TITLE
Allow Specification of mzML Files' Directory

### ISSUE THREAD

**Issue by DarioS** [rpeckner-broad/Specter#7]
The current interface allows one mzML file and one spectral library as input per execution. This means that the spectral library is imported once for each mzML file. Could there be an option to specify a directory of mzML files to be processed with a spectral library, thus avoiding the repeated importation of the library (e.g. I have 230 SCIEX SWATH files to process using a single spectral library) ?

**Comment by rpeckner-broad** [comment]
I've added a module MakePythonSpectralLib.py to the repo. Running it as `MakePythonSpectralLib.py <blibName.blib>` will produce a pickled Python dictionary with the name `blibName_PythonLibrary` that can be imported far more quickly than the blib. Note that you should still pass `<blibName>` to `Specter.sh`, without the `.blib` or `_PythonLibrary` extensions (it will recognize the `_PythonLibrary` version and import that instead of the blib). You can then run Specter.sh in a bash `for` loop over the files in your directory, i.e. 
```
#!/bin/bash
for filename in /my/mzml/directory/*.mzML; do
	./Specter.sh ... 
done
```
with the various arguments you want to specify.
