### ISSUE TITLE
Error in svd(X, nu = 0L) : infinite or missing values in 'x'

### ISSUE THREAD

**Issue by kaveelim** [rpeckner-broad/Specter#9]
Hello,

I try running the Specter with some public DIA data (e.g., PXD007052) and some of them has a problem in the Rscript step with the following error message.

"Error in svd(X, nu = 0L) : infinite or missing values in 'x'
Calls: lda -> lda.formula -> lda.default -> svd"

I think that the problem happen because no Decoy (or not enough Decoy) is left in the "quantsWithDecoys" dataframe. 

Do you have any suggestion?

Thank you.

**Comment by rpeckner-broad** [comment]
Hi, 
This is likely the same problem that was discussed in a previous issue #8. Did you run the analysis over all MS2 spectra or only a small subset thereof?

**Comment by kaveelim** [comment]
Thank you for your fast response.
In my case, I run all MS2 spectra which is 65733 MS2 spectra.
Here is the SpecterCoeffsDecoys.csv
https://drive.google.com/open?id=14naXTuRCUt3X1L3tBbH_W9wHkQz2yEPM

**Comment by rpeckner-broad** [comment]
As you point out, the problem is definitely the low number of decoy IDs. I'll rework the code so this doesn't produce an error.

**Comment by rpeckner-broad** [comment]
I've updated the code so it should work in your situation. Note that the "Score" column of the quant output will no longer be meaningful (all values will equal 1), since this is defined by the LDA. Rather than running the whole job again, you can just execute `Rscript SpecterQuant.R <mzML name> <blib name>` and it'll recognize the results you've already calculated.

**Comment by kaveelim** [comment]
Thank you.
